#!/usr/bin/env python3
"""
Plot mean schedule-delay delta (mixed - baseline) versus private-traffic value.

Assumptions:
- You have outputs/analysis/pt_delay.xlsx generated by export_pt_delay_excel.py
- The summary sheet contains columns: value, mean_delta_s
- X-axis uses 2 * value (zone2->1 + zone3->1)
- Log scale (symlog) on Y to handle zero/negative gracefully

Additionally saves a "heat curve" style plot with a smoothed line and
shaded band (rolling mean ± rolling std).

Usage:
  python plot_pt_delay.py --excel outputs/analysis/pt_delay.xlsx \
                          --out outputs/analysis/pt_delay.png \
                          --out-heat outputs/analysis/pt_delay_heat.png
"""

import argparse
import os
import pandas as pd
import matplotlib.pyplot as plt


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--excel", required=True, help="Path to pt_delay.xlsx")
    ap.add_argument("--out", required=True, help="Output image path (e.g., PNG)")
    ap.add_argument("--out-heat", required=False, help="Output path for heat-curve style plot")
    args = ap.parse_args()

    if not os.path.exists(args.excel):
        raise SystemExit(f"Excel not found: {args.excel}")

    xls = pd.ExcelFile(args.excel)
    if "summary" not in xls.sheet_names:
        raise SystemExit("summary sheet not found in Excel")

    df = pd.read_excel(args.excel, sheet_name="summary")
    if not {"value", "mean_delta_s"}.issubset(df.columns):
        raise SystemExit("summary sheet missing required columns: value, mean_delta_s")

    df = df.sort_values("value").copy()
    df["effective_value"] = df["value"] * 2  # account for two flows

    plt.figure(figsize=(8, 6))
    # Plot with traffic level on X-axis (effective_value) and delay on Y-axis
    plt.plot(df["effective_value"], df["mean_delta_s"], marker="o")
    plt.xlabel("Private OD volume (effective, zone2->1 + zone3->1)")
    plt.ylabel("Mean delay delta (s)")
    # Use symmetrical log scale on Y to handle zero/negative means without error
    plt.yscale("symlog", linthresh=1)
    plt.grid(True, which="both", linestyle=":", alpha=0.6)
    plt.tight_layout()
    plt.savefig(args.out, dpi=150)
    print(f"Plot saved: {args.out}")

    # Heat-curve style: rolling mean with shaded std band
    out_heat = args.out_heat
    if not out_heat:
        root, ext = os.path.splitext(args.out)
        out_heat = root + "_heat" + (ext or ".png")

    # Compute rolling stats (window=3 by default)
    df_roll = df[["effective_value", "mean_delta_s"]].copy()
    df_roll["mean"] = df_roll["mean_delta_s"].rolling(window=3, min_periods=1, center=True).mean()
    df_roll["std"] = df_roll["mean_delta_s"].rolling(window=3, min_periods=1, center=True).std().fillna(0)
    lower = df_roll["mean"] - df_roll["std"]
    upper = df_roll["mean"] + df_roll["std"]

    plt.figure(figsize=(8, 6))
    plt.plot(df_roll["effective_value"], df_roll["mean"], color="#1f77b4")
    plt.fill_between(df_roll["effective_value"], lower, upper, color="#1f77b4", alpha=0.2)
    plt.xlabel("Private OD volume (effective, zone2->1 + zone3->1)")
    plt.ylabel("Mean delay delta (s)")
    plt.yscale("symlog", linthresh=1)
    plt.grid(True, which="both", linestyle=":", alpha=0.6)
    plt.tight_layout()
    plt.savefig(out_heat, dpi=150)
    print(f"Heat-curve plot saved: {out_heat}")


if __name__ == "__main__":
    main()


